In [1]:
!pip install numpy --upgrade

     ---------------------------------------- 14.7/14.7 MB 3.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.5.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.22.3 which is incompatible.


In [2]:
import numpy as np

In [3]:
array_one = np.array([0,1,3,5,7,9])

array_one

array([0, 1, 3, 5, 7, 9])

In [4]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [5]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
array_of_ones = np.ones ((3,2), dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [10]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [14]:
array_of_floats = np.arange(1,3,0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [15]:
array_2D = np.array([(3,4,6),(2,1,6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [16]:
array_2D.shape

(2, 3)

In [17]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])