In [2]:
import numpy as np

In [3]:
p = np.array([9,8,7])
q = np.array([3,2,4])

In [4]:
p+q

array([12, 10, 11])

In [5]:
p-q

array([6, 6, 3])

In [6]:
print('p * q = ', p*q)
print('p / q = ', p/q)
print('p % q = ', p%q)

p * q =  [27 16 28]
p / q =  [3.   4.   1.75]
p % q =  [0 0 3]


In [7]:
p % 2

array([1, 0, 1], dtype=int32)

In [8]:
p > 8

array([ True, False, False])

In [9]:
p < 9

array([False,  True,  True])

In [11]:
x = np.array([[2,1], [1,3]])
y = np.array([[3,2], [4,2]])

print('x: \n', x)
print('y: \n', y)

x: 
 [[2 1]
 [1 3]]
y: 
 [[3 2]
 [4 2]]


In [12]:
x + y

array([[5, 3],
       [5, 5]])

In [13]:
x - y

array([[-1, -1],
       [-3,  1]])

In [14]:
x * y

array([[6, 2],
       [4, 6]])

In [15]:
x.dot(y)

array([[10,  6],
       [15,  8]])

In [16]:
np.dot(x,y)

array([[10,  6],
       [15,  8]])

In [17]:
x *= 4
x

array([[ 8,  4],
       [ 4, 12]])

In [21]:
fleet_mileage = np.array([14130, 37234, 21892, 11479, 6890, 27981])

In [22]:
fleet_mileage.sum()

119606

In [23]:
fleet_mileage.min()

6890

In [24]:
fleet_mileage.max()

37234

In [25]:
print('Mean: ', fleet_mileage.mean())

Mean:  19934.333333333332


In [27]:
num = np.arange (16).reshape(4,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
num.sum()

120

In [30]:
num.sum(axis=0)

array([24, 28, 32, 36])

In [31]:
num.sum(axis=1)

array([ 6, 22, 38, 54])

In [32]:
num.min(axis=1)

array([ 0,  4,  8, 12])

In [33]:
num.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])