In [1]:
import numpy as np

In [2]:
x = np.arange(10)**3

x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
x[3]

27

In [4]:
x[-4]

216

In [5]:
x[1 : 8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [6]:
x[3 : -3]

array([ 27,  64, 125, 216], dtype=int32)

In [7]:
x[ : 8]

array([  0,   1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [8]:
x[3 : ]

array([ 27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
x[ : 10: 2]

array([  0,   8,  64, 216, 512], dtype=int32)

In [10]:
x[ : : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [12]:
companies = np.array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
                      [1938, 1975, 1911, 2006, 2007],
                      [489000, 131000, 380000, 3000, 30000]])

In [13]:
companies

array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U11')

In [14]:
companies[0]

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'], dtype='<U11')

In [15]:
companies[:, 2]

array(['IBM', '1911', '380000'], dtype='<U11')

In [16]:
companies[0, 2]

'IBM'

In [17]:
companies[0:2, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006']], dtype='<U11')

In [18]:
companies[:, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006'],
       ['380000', '3000']], dtype='<U11')

In [19]:
companies[-1, :]

array(['489000', '131000', '380000', '3000', '30000'], dtype='<U11')

In [20]:
companies[0, ...]

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'], dtype='<U11')

In [21]:
companies[..., 2]

array(['IBM', '1911', '380000'], dtype='<U11')