In [1]:
import numpy as np

In [2]:
circle_radii = np.array([145, 120, 90, 60, 45, 30])

In [3]:
circle_diameters = 2 * circle_radii
circle_diameters

array([290, 240, 180, 120,  90,  60])

In [4]:
circle_areas = np.pi * circle_radii**2
circle_areas

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

In [5]:
angle_degrees = np.array([0, 30, 60, 90, 120, 150, 180])

In [6]:
angle_radians = np.pi * angle_degrees / 180
angle_radians

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

In [7]:
print('Sine Values:')
np.sin(angle_radians)

Sine Values:


array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       8.66025404e-01, 5.00000000e-01, 1.22464680e-16])

In [8]:
print('Cosine Values:')
np.cos(angle_radians)

Cosine Values:


array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -8.66025404e-01, -1.00000000e+00])

In [9]:
print('Tangent Values:')
np.tan(angle_radians)

Tangent Values:


array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16])

In [10]:
sine_values = np.sin(angle_radians)

In [11]:
arcsine_values = np.arcsin(sine_values)
arcsine_values

array([0.00000000e+00, 5.23598776e-01, 1.04719755e+00, 1.57079633e+00,
       1.04719755e+00, 5.23598776e-01, 1.22464680e-16])

In [12]:
arcsine_values * 180 / np.pi

array([0.0000000e+00, 3.0000000e+01, 6.0000000e+01, 9.0000000e+01,
       6.0000000e+01, 3.0000000e+01, 7.0167093e-15])

In [13]:
x = np.arange(4, 31, 5)
x

array([ 4,  9, 14, 19, 24, 29])

In [14]:
expo = np.exp(x)
expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

In [15]:
sqrt = np.sqrt(x)
sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

In [16]:
np.median(x)

16.5

In [19]:
float_values = np.genfromtxt('datasets/float_values.csv', delimiter=',')

In [20]:
float_values

array([0.8944, 0.8898, 0.8894, ..., 0.7051, 0.6992, 0.7047])

In [21]:
float_values.shape

(5998,)

In [22]:
print('Mean: %i' %np.mean(float_values))
print('Median: %i' %np.median(float_values))
print('Variance: %i' %np.var(float_values))
print('Standard Deviation: %i' %np.std(float_values))

Mean: 16
Median: 5
Variance: 1659
Standard Deviation: 40
